export LS_COLORS=$(cat /Users/$(whoami)/.dotfiles/zsh/ls_colors_snazzy_8bit)

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export GOPATH=$HOME/Development/go

export ANDROID_HOME=/Users/$(whoami)/Library/Android/sdk

export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/

if [ -d "/Applications/Emacs.app/Contents/MacOS/bin" ]; then
  export PATH="/Applications/Emacs.app/Contents/MacOS/bin:$PATH"
  alias emacs="emacs -nw" # Always launch "emacs" in terminal mode.
fi

eval `/usr/libexec/path_helper -s`
eval $(/opt/homebrew/bin/brew shellenv)
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
# Created by `pipx` on 2024-08-30 07:25:03
export PATH="$PATH:/Users/neri/.local/bin"

export USE_GKE_GCLOUD_AUTH_PLUGIN=True
