DISABLE_AUTO_UPDATE=true
ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"

source ~/.dotfiles/zsh/plugins.sh

alias difff='git --no-pager diff --color=auto --no-ext-diff --no-index'
alias k=kubectl
export FZF_DEFAULT_OPTS='--bind=up:preview-up,down:preview-down'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
